### PR TITLE
Added cucumber support

### PR DESCRIPTION
**Pull request by AutomationReddy**
@carmenmitru Please take a look at this PR. Added Cucumber support. 

If you are good with the changes, can you please publish the library to npm, so that we can close few tickets. 

Also, can we move this repo to [Webdriverio Community](https://github.com/webdriverio-community)

### CODE REVIEW

**Comment by carmenmitru** [comment]
@AutomationReddy  Thanks for you submit and also for your time to add new features.

**Comment by carmenmitru** [comment]
@AutomationReddy  I take a look on it and publish it.

Regards,

Carmen

**Comment by AutomationReddy** [comment]
@carmenmitru Thanks for looking into it. Please pull the latest. I have just modified error variable for after tests.

**Comment by carmenmitru** [comment]
@AutomationReddy  I published a new version.

**Comment by AutomationReddy** [comment]
@carmenmitru Thanks. Looking forward to new  version from this PR.

**Comment by AutomationReddy** [comment]
@carmenmitru Just checking, did you get a chance to look into this? Needed this for our project with latest cucumber feature. Your help is much appreciated.

**Pull request merged**
